-- ============================================================
-- FOOTBALL MANAGEMENT SYSTEM
-- CREATE TABLES
-- ============================================================

USE FOOTBALL_MANAGEMENT_SYSTEM;
GO

-- Create the CONTRIES table.
-- Stores countries and their unique country codes.

CREATE TABLE COUNTRIES
(
    COUNTRY_ID VARCHAR(5),
    COUNTRY_NAME NVARCHAR(60) NOT NULL,

    CONSTRAINT PK_COUNTRIES
        PRIMARY KEY (COUNTRY_ID)
);
GO

-- Create the STADIUMS table.
-- Stores stadium information.

CREATE TABLE STADIUMS
(
    STADIUM_ID VARCHAR(5),
    STADIUM_NAME NVARCHAR(100) NOT NULL,
    ADDRESS NVARCHAR(200),

    CONSTRAINT PK_STADIUMS
        PRIMARY KEY (STADIUM_ID)
);
GO

-- Create the PROVINCES table.
-- Stores province/city information.

CREATE TABLE PROVINCES
(
    PROVINCE_ID VARCHAR(5),
    PROVINCE_NAME NVARCHAR(100) NOT NULL,

    CONSTRAINT PK_PROVINCES
        PRIMARY KEY (PROVINCE_ID)
);
GO

-- Create the CLUBS table.
-- Stores football club information and its stadium/province relationships.

CREATE TABLE CLUBS
(
    CLUB_ID VARCHAR(5),
    CLUB_NAME NVARCHAR(100) NOT NULL,
    STADIUM_ID VARCHAR(5) NOT NULL,
    PROVINCE_ID VARCHAR(5) NOT NULL,

    CONSTRAINT PK_CLUBS
        PRIMARY KEY (CLUB_ID),

    CONSTRAINT FK_STADIUMS_CLUBS
        FOREIGN KEY (STADIUM_ID)
        REFERENCES STADIUMS(STADIUM_ID),

    CONSTRAINT FK_PROVINCES_CLUBS
        FOREIGN KEY (PROVINCE_ID)
        REFERENCES PROVINCES(PROVINCE_ID)
);
GO

-- Create the PLAYERS table.
-- Stores player information.

CREATE TABLE PLAYERS
(
    PLAYER_ID NUMERIC IDENTITY(1,1),
    PLAYER_NAME NVARCHAR(100) NOT NULL,
    POSITION NVARCHAR(20) NOT NULL,
    DATE_OF_BIRTH DATETIME,
    ADDRESS NVARCHAR(200),
    CLUB_ID VARCHAR(5) NOT NULL,
    COUNTRY_ID VARCHAR(5) NOT NULL,
    JERSEY_NUMBER INT NOT NULL,

    CONSTRAINT PK_PLAYERS
        PRIMARY KEY (PLAYER_ID),

    CONSTRAINT FK_CLUBS_PLAYERS
        FOREIGN KEY (CLUB_ID)
        REFERENCES CLUBS(CLUB_ID),

    CONSTRAINT FK_COUNTRIES_PLAYERS
        FOREIGN KEY (COUNTRY_ID)
        REFERENCES COUNTRIES(COUNTRY_ID)
);
GO

-- Create the COACHES table.
-- Stores coach information.

CREATE TABLE COACHES
(
    COACH_ID VARCHAR(5),
    COACH_NAME NVARCHAR(100) NOT NULL,
    DATE_OF_BIRTH DATETIME,
    ADDRESS NVARCHAR(200),
    PHONE NVARCHAR(20),
    COUNTRY_ID VARCHAR(5) NOT NULL,

    CONSTRAINT PK_COACHES
        PRIMARY KEY (COACH_ID),

    CONSTRAINT FK_COUNTRIES_COACHES
        FOREIGN KEY (COUNTRY_ID)
        REFERENCES COUNTRIES(COUNTRY_ID)
);
GO

-- Create the COACH_CLUB table.
-- Associates coaches with clubs and stores their roles.

CREATE TABLE COACH_CLUB
(
    COACH_ID VARCHAR(5),
    CLUB_ID VARCHAR(5),
    ROLE NVARCHAR(100) NOT NULL,

    CONSTRAINT PK_COACH_CLUB
        PRIMARY KEY (COACH_ID, CLUB_ID),

    CONSTRAINT FK_COACHES_COACH_CLUB
        FOREIGN KEY (COACH_ID)
        REFERENCES COACHES(COACH_ID),

    CONSTRAINT FK_CLUBS_COACH_CLUB
        FOREIGN KEY (CLUB_ID)
        REFERENCES CLUBS(CLUB_ID)
);
GO

-- Create the MATCHES table.
-- Stores match information.

CREATE TABLE MATCHES
(
    MATCH_ID NUMERIC IDENTITY(1,1),
    SEASON INT NOT NULL,
    ROUND INT NOT NULL,
    MATCH_DATE DATETIME NOT NULL,
    HOME_CLUB_ID VARCHAR(5) NOT NULL,
    AWAY_CLUB_ID VARCHAR(5) NOT NULL,
    STADIUM_ID VARCHAR(5) NOT NULL,
    RESULT VARCHAR(5) NOT NULL,

    CONSTRAINT PK_MATCHES
        PRIMARY KEY (MATCH_ID),

    CONSTRAINT FK_HOME_CLUB_MATCHES
        FOREIGN KEY (HOME_CLUB_ID)
        REFERENCES CLUBS(CLUB_ID),

    CONSTRAINT FK_AWAY_CLUB_MATCHES
        FOREIGN KEY (AWAY_CLUB_ID)
        REFERENCES CLUBS(CLUB_ID),

    CONSTRAINT FK_STADIUMS_MATCHES
        FOREIGN KEY (STADIUM_ID)
        REFERENCES STADIUMS(STADIUM_ID)
);
GO

-- Create the STANDINGS table.
-- Stores league standings.

CREATE TABLE STANDINGS
(
    CLUB_ID VARCHAR(5),
    SEASON INT,
    ROUND INT,
    MATCHES_PLAYED INT NOT NULL,
    WINS INT NOT NULL,
    DRAWS INT NOT NULL,
    LOSSES INT NOT NULL,
    GOAL_DIFFERENCE VARCHAR(5) NOT NULL,
    POINTS INT NOT NULL,
    RANK INT NOT NULL,

    CONSTRAINT PK_STANDINGS
        PRIMARY KEY (CLUB_ID, SEASON, ROUND),

    CONSTRAINT FK_CLUBS_STANDINGS
        FOREIGN KEY (CLUB_ID)
        REFERENCES CLUBS(CLUB_ID)
);
GO