SELECT *
    FROM PLAYER
    ORDER BY PLAYER_NAME


SELECT PLAYER_NAME, BIRTH_DATE
    FROM PLAYER
    ORDER BY BIRTH_DATE DESC


SELECT PLAYER_NAME, JERSEY_NUMBER
    FROM PLAYER
    ORDER BY JERSEY_NUMBER


SELECT PLAYER_NAME, POSITION
    FROM PLAYER
    ORDER BY POSITION,
            PLAYER_NAME


SELECT PLAYER_NAME AS Name
    FROM PLAYER
    ORDER BY Name