USE master
GO

-- Câu 1:
-- Tạo CSDL có tên là QL_CONGTRINH.

CREATE DATABASE QL_CONGTRINH
GO

USE QL_CONGTRINH
GO


-- ============================================================
-- Câu 2:
-- Tạo các Table trong cơ sở dữ liệu QL_CONGTRINH.
--
-- Các bảng cần tạo:
-- KTRUCSU
-- CHUTHAU
-- CHUNHAN
-- CONGNHAN
-- CONGTRINH
-- THAMGIA
-- THIETKE
-- ============================================================

CREATE TABLE KTRUCSU
(
	HOTEN_KTS NVARCHAR(100),
	NAMS_KTS INT,
	PHAI NVARCHAR(3),
	NOI_TN NVARCHAR(200),
	DCHI_LL_KTS NVARCHAR(200),
	CONSTRAINT PK_KTRUCSU PRIMARY KEY(HOTEN_KTS)
)
GO

CREATE TABLE CHUTHAU
(
	TEN_THAU NVARCHAR(100),
	TEL NVARCHAR(20) NOT NULL,
	DCHI_THAU NVARCHAR(200),
	CONSTRAINT PK_CHUTHAU PRIMARY KEY(TEN_THAU)
)
GO

CREATE TABLE CHUNHAN
(
	TEN_CHU NVARCHAR(100),
	DCHI_CHU NVARCHAR(200) NOT NULL,
	CONSTRAINT PK_CHUNHAN PRIMARY KEY(TEN_CHU)
)
GO

CREATE TABLE CONGNHAN
(
	HOTEN_CN NVARCHAR(100),
	NAMS_CN INT,
	NAM_VAO_N DATETIME,
	CH_MON NVARCHAR(200),
	CONSTRAINT PK_CONGNHAN PRIMARY KEY(HOTEN_CN)
)
GO

CREATE TABLE CONGTRINH
(
	STT_CTR NUMERIC IDENTITY(1,1),
	TEN_CTR NVARCHAR(200) NOT NULL,
	DCHI_CTR NVARCHAR(200),
	TINH_THANH NVARCHAR(100),
	KINH_PHI FLOAT,
	TEN_CHU NVARCHAR(100) NOT NULL,
	TEN_THAU NVARCHAR(100) NOT NULL,
	NGAY_BD DATETIME,
	CONSTRAINT PK_CONGTRINH PRIMARY KEY(STT_CTR),
	CONSTRAINT FK_CHUNHAN_CT FOREIGN KEY(TEN_CHU)
								REFERENCES CHUNHAN(TEN_CHU),
	CONSTRAINT FK_CHUTHAU_CT FOREIGN KEY(TEN_THAU)
								REFERENCES CHUTHAU(TEN_THAU)
)
GO

CREATE TABLE THAMGIA
(
	HOTEN_CN NVARCHAR(100),
	STT_CTR NUMERIC,
	NGAY_TGIA DATETIME,
	SO_NGAY INT,
	CONSTRAINT PK_THAMGIA PRIMARY KEY(HOTEN_CN,STT_CTR),
	CONSTRAINT FK_CONGNHAN_TG FOREIGN KEY(HOTEN_CN)
								REFERENCES CONGNHAN(HOTEN_CN),
	CONSTRAINT FK_CONGTRINH_TG FOREIGN KEY(STT_CTR)
								REFERENCES CONGTRINH(STT_CTR)
)
GO

CREATE TABLE THIETKE
(
	HOTEN_KTS NVARCHAR(100),
	STT_CTR NUMERIC,
	THU_LAO FLOAT,
	CONSTRAINT PK_THIETKE PRIMARY KEY(HOTEN_KTS,STT_CTR),
	CONSTRAINT FK_KTRUCSU_TK FOREIGN KEY(HOTEN_KTS)
								REFERENCES KTRUCSU(HOTEN_KTS),
	CONSTRAINT FK_CONGTRINH_TK FOREIGN KEY(STT_CTR)
								REFERENCES CONGTRINH(STT_CTR)
)
GO


-- Câu 3:
-- Tạo liên kết giữa các Table trong cơ sở dữ liệu QL_CONGTRINH.

-- Các liên kết được tạo thông qua FOREIGN KEY:
-- 	CONGTRINH.TEN_CHU  -> CHUNHAN.TEN_CHU
-- 	CONGTRINH.TEN_THAU -> CHUTHAU.TEN_THAU
-- 	THAMGIA.HOTEN_CN   -> CONGNHAN.HOTEN_CN
-- 	THAMGIA.STT_CTR    -> CONGTRINH.STT_CTR
-- 	THIETKE.HOTEN_KTS  -> KTRUCSU.HOTEN_KTS
-- 	THIETKE.STT_CTR    -> CONGTRINH.STT_CTR

-- Các FOREIGN KEY đã được khai báo trực tiếp trong CREATE TABLE.


-- Câu 4:
-- Xem mô hình liên kết giữa các Table trong CSDL.

-- Thực hiện bằng Database Diagrams trong SQL Server Management Studio.